accounts:
- account_id: '172327596604'
  name: engg
  regions:
  - us-east-1
  role: arn:aws:iam::172327596604:role/CloudCustodian-ExecutionRole
  # profile: engg # local
  vars:
    environment: engg
  tags:
  - environment:engg
  - ou:aikyam
