image:
  name: 140253569749.dkr.ecr.us-west-2.amazonaws.com/gs-ecr-shared-uw2-bitbucket-terraform:141
  aws:
    oidc-role: arn:aws:iam::140253569749:role/devops/bitbucket-image

definitions:
  services:
    docker:
      memory: 2048
  conditions:
    - condition: &all_changes
        changesets:
          includePaths:
          - '**'
  scripts:
    - script: &prep_plan |
        export TF_IN_AUTOMATION=1
        mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/plans
        tfenv install && tfenv use
    - script: &prep_apply |
        export TF_IN_AUTOMATION=1
        tfenv install && tfenv use
    - script: &configure_state_manager |
        mkdir -p ~/.aws && touch ~/.aws/credentials
        echo $BITBUCKET_STEP_OIDC_TOKEN > /tmp/web-identity-token
        cat > ~/.aws/credentials <<-EOF
          [backend]
          role_arn=arn:aws:iam::140253569749:role/devops/gs-iam-shared-terraform-state-manager
          web_identity_token_file=/tmp/web-identity-token
        EOF
    - script: &assume_role_cloud_admin_shared |
        credentials=$(aws sts assume-role-with-web-identity \
          --role-arn arn:aws:iam::140253569749:role/devops/cloud-admin \
          --role-session-name bitbucket-c7n-${BITBUCKET_BUILD_NUMBER} \
          --web-identity-token "${BITBUCKET_STEP_OIDC_TOKEN}" \
          --query Credentials)
        AWS_DEFAULT_REGION=us-west-2
        AWS_ACCESS_KEY_ID=$(echo $credentials | jq -r '.AccessKeyId')
        AWS_SECRET_ACCESS_KEY=$(echo $credentials | jq -r '.SecretAccessKey')
        AWS_SESSION_TOKEN=$(echo $credentials | jq -r '.SessionToken')
        export AWS_DEFAULT_REGION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
    - script: &install_c7n |
        apt-get update
        pip install --upgrade pip
        apt install -y python3.10-venv
        python3 -m venv custodian
        source custodian/bin/activate
        pip install -r requirements.txt
    - script: &bootstrap_greenstreet_utils |
        bootstrap_greenstreet_utils.sh 0.1.46
        ssk scripts -o ${BITBUCKET_CLONE_DIR}/scripts


  steps:
    # Terraform plan steps
    - step: &plan_infrastructure_root-us-west-2
        name: plan infrastructure root-us-west-2
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_plan
          - *configure_state_manager
          - terraform init -reconfigure -input=false
          - terraform workspace select root-us-west-2 || terraform workspace new root-us-west-2
          - terraform plan -input=false -out ${BITBUCKET_CLONE_DIR}/artifacts/plans/root-us-west-2.plan
        artifacts:
          - artifacts/plans/**
    - step: &plan_infrastructure_shared-us-west-2
        name: plan infrastructure shared-us-west-2
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_plan
          - *configure_state_manager
          - terraform init -reconfigure -input=false
          - terraform workspace select shared-us-west-2 || terraform workspace new shared-us-west-2
          - terraform plan -input=false -out ${BITBUCKET_CLONE_DIR}/artifacts/plans/shared-us-west-2.plan
        artifacts:
          - artifacts/plans/**
    - step: &plan_infrastructure_audit-us-west-2
        name: plan infrastructure audit-us-west-2
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_plan
          - *configure_state_manager
          - terraform init -reconfigure -input=false
          - terraform workspace select audit-us-west-2 || terraform workspace new audit-us-west-2
          - terraform plan -input=false -out ${BITBUCKET_CLONE_DIR}/artifacts/plans/audit-us-west-2.plan
        artifacts:
          - artifacts/plans/**
    - step: &plan_infrastructure_log-us-west-2
        name: plan infrastructure log-us-west-2
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_plan
          - *configure_state_manager
          - terraform init -reconfigure -input=false
          - terraform workspace select log-us-west-2 || terraform workspace new log-us-west-2
          - terraform plan -input=false -out ${BITBUCKET_CLONE_DIR}/artifacts/plans/log-us-west-2.plan
        artifacts:
          - artifacts/plans/**
    - step: &plan_infrastructure_development-us-west-2
        name: plan infrastructure development-us-west-2
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_plan
          - *configure_state_manager
          - terraform init -reconfigure -input=false
          - terraform workspace select development-us-west-2 || terraform workspace new development-us-west-2
          - terraform plan -input=false -out ${BITBUCKET_CLONE_DIR}/artifacts/plans/development-us-west-2.plan
        artifacts:
          - artifacts/plans/**
    - step: &plan_infrastructure_staging-us-west-2
        name: plan infrastructure staging-us-west-2
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_plan
          - *configure_state_manager
          - terraform init -reconfigure -input=false
          - terraform workspace select staging-us-west-2 || terraform workspace new staging-us-west-2
          - terraform plan -input=false -out ${BITBUCKET_CLONE_DIR}/artifacts/plans/staging-us-west-2.plan
        artifacts:
          - artifacts/plans/**
    - step: &plan_infrastructure_production-us-west-2
        name: plan infrastructure production-us-west-2
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_plan
          - *configure_state_manager
          - terraform init -reconfigure -input=false
          - terraform workspace select production-us-west-2 || terraform workspace new production-us-west-2
          - terraform plan -input=false -out ${BITBUCKET_CLONE_DIR}/artifacts/plans/production-us-west-2.plan
        artifacts:
          - artifacts/plans/**

    # Terraform apply steps
    - step: &apply_infrastructure
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - infrastructure/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/infrastructure
          - *prep_apply
          - *configure_state_manager
          - terraform init -input=false
          - terraform workspace select ${BITBUCKET_DEPLOYMENT_ENVIRONMENT}
          - terraform apply -auto-approve ${BITBUCKET_CLONE_DIR}/artifacts/plans/${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.plan

    # c7n steps
    - step: &c7n_validate_pr
        name: pr - custodian validate & dry run
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-validation
          - *assume_role_cloud_admin_shared
          - custodian validate policies/*
          - ./scripts/deploy-updated-policies.sh -t -d
        artifacts:
          - artifacts/c7n-validation/**
    - step: &c7n_validate
        name: custodian validate & dry run
        oidc: true
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-validation
          - *assume_role_cloud_admin_shared
          - custodian validate policies/*
          - ./scripts/deploy-updated-policies.sh -d
        artifacts:
          - artifacts/c7n-validation/**
    - step: &c7n_deploy_mailer
        name: custodian deploy c7n-mailer
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/c7n-mailer
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-mailer.sh
        artifacts:
          - artifacts/c7n-deploy/**
    - step: &c7n_deploy_root
        name: custodian deploy root
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/root
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-updated-policies.sh -a root
        artifacts:
          - artifacts/c7n-deploy/**
    - step: &c7n_deploy_shared
        name: custodian deploy shared
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/shared
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-updated-policies.sh -a shared
        artifacts:
          - artifacts/c7n-deploy/**
    - step: &c7n_deploy_audit
        name: custodian deploy audit
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/audit
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-updated-policies.sh -a audit
        artifacts:
          - artifacts/c7n-deploy/**
    - step: &c7n_deploy_log
        name: custodian deploy log
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/log
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-updated-policies.sh -a log
        artifacts:
          - artifacts/c7n-deploy/**
    - step: &c7n_deploy_development
        name: custodian deploy development
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/development
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-updated-policies.sh -a development
        artifacts:
          - artifacts/c7n-deploy/**
    - step: &c7n_deploy_staging
        name: custodian deploy staging
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/staging
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-updated-policies.sh -a staging
        artifacts:
          - artifacts/c7n-deploy/**
    - step: &c7n_deploy_production
        name: custodian deploy production
        oidc: true
        trigger: manual
        services:
          - docker
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - c7n/**
        script:
          - cd ${BITBUCKET_CLONE_DIR}/c7n
          - *install_c7n
          - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/production
          - *assume_role_cloud_admin_shared
          - ./scripts/deploy-updated-policies.sh -a production
        artifacts:
          - artifacts/c7n-deploy/**

    # Docs steps
    - step: &publish_docs
        name: publish docs
        oidc: true
        condition:
          changesets:
            includePaths:
              - bitbucket-pipelines.yml
              - docs/**
        script:
          - *bootstrap_greenstreet_utils
          - export ENVIRONMENT=development
          - source ${BITBUCKET_CLONE_DIR}/scripts/assume_aws_role.sh "arn:aws:iam::793362518373:role/devops/cloud-admin"
          - ssk docs -s DEVOPS -dr ${BITBUCKET_CLONE_DIR}/docs -cd ${BITBUCKET_CLONE_DIR}/docs/config -p
          - source ${BITBUCKET_CLONE_DIR}/scripts/reset_aws_role.sh


pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *plan_infrastructure_root-us-west-2
        - step: *plan_infrastructure_shared-us-west-2
        - step: *plan_infrastructure_audit-us-west-2
        - step: *plan_infrastructure_log-us-west-2
        - step: *plan_infrastructure_development-us-west-2
        - step: *plan_infrastructure_staging-us-west-2
        - step: *plan_infrastructure_production-us-west-2
        - step: *c7n_validate_pr
  branches:
    # '**':
    main:
      - step: *publish_docs
      - parallel:
        - step: *plan_infrastructure_root-us-west-2
        - step: *plan_infrastructure_shared-us-west-2
        - step: *plan_infrastructure_audit-us-west-2
        - step: *plan_infrastructure_log-us-west-2
        - step: *plan_infrastructure_development-us-west-2
        - step: *plan_infrastructure_staging-us-west-2
        - step: *plan_infrastructure_production-us-west-2
        - step: *c7n_validate
      - parallel:
        - step:
            <<: *apply_infrastructure
            name: apply infrastructure root-us-west-2
            deployment: root-us-west-2
        - step:
            <<: *apply_infrastructure
            name: apply infrastructure shared-us-west-2
            deployment: shared-us-west-2
        - step:
            <<: *apply_infrastructure
            name: apply infrastructure audit-us-west-2
            deployment: audit-us-west-2
        - step:
            <<: *apply_infrastructure
            name: apply infrastructure log-us-west-2
            deployment: log-us-west-2
        - step:
            <<: *apply_infrastructure
            name: apply infrastructure development-us-west-2
            deployment: development-us-west-2
        - step:
            <<: *apply_infrastructure
            name: apply infrastructure staging-us-west-2
            deployment: staging-us-west-2
        - step:
            <<: *apply_infrastructure
            name: apply infrastructure production-us-west-2
            deployment: production-us-west-2
        - step: *c7n_deploy_mailer
        - step: *c7n_deploy_root
        - step: *c7n_deploy_shared
        - step: *c7n_deploy_audit
        - step: *c7n_deploy_log
        - step: *c7n_deploy_development
        - step: *c7n_deploy_staging
        - step: *c7n_deploy_production


  # Custom pipelines for clean up
  custom:
    deploy-all-policies:
      - variables:
          - name: ACCOUNT_NAME
            default: development
            allowed-values:
              - development
              - staging
              - production
              - shared
              - audit
              - log
              - root

      - step:
          name: custodian deploy all policies to account
          oidc: true
          services:
            - docker
          script:
            - cd ${BITBUCKET_CLONE_DIR}/c7n
            - *install_c7n
            - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-deploy/${ACCOUNT_NAME}
            - *assume_role_cloud_admin_shared
            - ./scripts/deploy-policies.sh -a ${ACCOUNT_NAME}
          artifacts:
            - artifacts/c7n-deploy/**

    garbage-collection-dry-run:
      - step:
          name: clean orphaned policy resources (dry run)
          oidc: true
          services:
            - docker
          script:
            - cd ${BITBUCKET_CLONE_DIR}/c7n
            - *install_c7n
            - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-cleanup
            - *assume_role_cloud_admin_shared
            - ./scripts/clean-removed-policies.sh -d
          artifacts:
            - artifacts/c7n-cleanup/**

    garbage-collection:
      - step:
          name: clean orphaned policy resources
          oidc: true
          services:
            - docker
          script:
            - cd ${BITBUCKET_CLONE_DIR}/c7n
            - *install_c7n
            - mkdir -p ${BITBUCKET_CLONE_DIR}/artifacts/c7n-cleanup
            - *assume_role_cloud_admin_shared
            - ./scripts/clean-removed-policies.sh
          artifacts:
            - artifacts/c7n-cleanup/**

    publish-docs:
      - step: 
          <<: *publish_docs
          condition: *all_changes
